# Generated by Django 4.2.27 on 2026-02-01 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('evidence', models.TextField(help_text='Evidence and lived experience supporting this motion')),
                ('proposed_action', models.TextField()),
                ('resource_ask', models.TextField(help_text='Micro-budget and resource requirements')),
                ('success_measures', models.TextField()),
                ('jurisdiction', models.CharField(choices=[('local', 'Local Council'), ('state', 'NSW State'), ('federal', 'Commonwealth')], default='local', max_length=20)),
                ('lga', models.CharField(choices=[('newcastle', 'Newcastle'), ('lake_macquarie', 'Lake Macquarie'), ('port_stephens', 'Port Stephens')], max_length=20)),
                ('safeguarding_considerations', models.TextField(blank=True)),
                ('inclusion_considerations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('modified', 'Modified'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('delivery_status', models.CharField(choices=[('not_started', 'Not Started'), ('on_track', 'On Track'), ('delayed', 'Delayed'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('response_deadline', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MotionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accept', 'Accept'), ('modify', 'Modify'), ('reject', 'Reject')], max_length=10)),
                ('reasons', models.TextField(help_text='Explanation in plain English')),
                ('delivery_plan', models.TextField(blank=True)),
                ('milestones', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('alternative_pathway', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accountable_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
                ('motion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='motions.motion')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='motions.motion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('approve', 'Approve'), ('disapprove', 'Disapprove')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='motions.motion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('motion', 'user')},
            },
        ),
    ]
