# Generated by Django 4.2.27 on 2026-02-01 05:10

from django.db import migrations


def create_superuser(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    if not User.objects.filter(username='admin').exists():
        user = User(
            username='admin',
            email='admin@odyssey.local',
            is_staff=True,
            is_superuser=True,
            lga='newcastle',
            role='admin',
        )
        user.set_password('admin123')
        user.save()


def remove_superuser(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(username='admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser, remove_superuser),
    ]
